export const MOCK_ITINERARIES = [
  {
    _id: "mock-norway-lofoten-summer-loop",
    titleZh: "羅弗敦群島 5 天自駕精選",
    titleEn: "Lofoten Highlights in 5 Days",
    slug: "lofoten-highlights-5d",
    descriptionZh: "用 5 天把漁村、公路風景與經典觀景點串成一條節奏舒服的羅弗敦初訪路線。",
    descriptionEn: "A first-time Lofoten route that strings together fishing villages, scenic drives, and the region's signature viewpoints.",
    country: "Norway",
    purpose: "leisure",
    transportMode: "car",
    pace: "moderate",
    budget: "mid_range",
    seasons: ["summer", "autumn"],
    arrivalTime: "noon",
    departureTime: "morning",
    durationDays: 5,
    featured: true,
    days: [
      {
        dayNumber: 1,
        titleZh: "抵達與海港開場",
        titleEn: "Arrival and Harbor Warm-up",
        summaryZh: "從機場進入羅弗敦節奏，先用兩個停點讓身體進到北方的光線裡。",
        summaryEn: "Ease into the islands with a gentle arrival day and two stops that set the northern mood.",
        stops: [
          {
            time: "13:00",
            labelZh: "抵達 Svolvaer",
            labelEn: "Arrive in Svolvaer",
            noteZh: "取車後先沿海港散步，調整作息與光線節奏。",
            noteEn: "Pick up the car and start with a calm harbor walk to settle into the region.",
            durationMinutes: 90,
            photoTipZh: "傍晚逆光時港邊的船影最有層次。",
            photoTipEn: "Late-afternoon backlight gives the harbor boats the best depth.",
            mealAdviceZh: "第一餐以海鮮湯或簡單 fish soup 為主，份量和節奏都比較剛好。",
            mealAdviceEn: "A simple fish soup makes an easy first meal after arrival.",
          },
          {
            time: "17:30",
            labelZh: "Svolvaer 海港晚餐",
            labelEn: "Dinner by Svolvaer Harbor",
            noteZh: "安排一間步行可到的餐廳，避免第一天開車太晚。",
            noteEn: "Keep dinner walkable so the first driving day stays light.",
            durationMinutes: 120,
            hotelAdviceZh: "第一晚住 Svolvaer，隔天往西推進最順。",
            hotelAdviceEn: "Staying in Svolvaer on night one makes the next day's westbound drive easier.",
          },
        ],
      },
      {
        dayNumber: 2,
        titleZh: "經典漁村公路日",
        titleEn: "Classic Fishing Village Drive",
        summaryZh: "把 Hamnoy、Reine 和沿線觀景點壓成一條最漂亮的西段公路。",
        summaryEn: "Spend the day on Lofoten's most photogenic western stretch.",
        stops: [
          {
            time: "10:00",
            labelZh: "Hamnoy Viewpoint",
            labelEn: "Hamnoy Viewpoint",
            noteZh: "上午保留停車與拍照時間，不要只拍一張就走。",
            noteEn: "Leave real time for parking and photos instead of treating it as a quick stop.",
            durationMinutes: 60,
            photoTipZh: "橋上構圖最穩，但風大時手機要抓緊。",
            photoTipEn: "The bridge gives the cleanest composition, but the wind can be strong.",
          },
          {
            time: "13:30",
            labelZh: "Reine 散步",
            labelEn: "Reine Walk",
            noteZh: "中段放慢節奏，讓視覺和交通都稍微休息。",
            noteEn: "Slow down here to give both your eyes and the road some breathing room.",
            durationMinutes: 120,
            personalAdviceZh: "這一段不要排太多點，留白反而更像在旅行。",
            personalAdviceEn: "Don't overpack this section; the empty space is part of the experience.",
          },
        ],
      },
      {
        dayNumber: 3,
        titleZh: "留白探索日",
        titleEn: "Open Exploration Day",
        summaryZh: "把最喜歡的點重訪一次，或換成小型步道和咖啡館。",
        summaryEn: "Use the day for re-visits, smaller hikes, or a relaxed cafe rhythm.",
        stops: [
          {
            time: "09:30",
            labelZh: "彈性補景點",
            labelEn: "Flexible Return Stop",
            noteZh: "依天氣決定是補拍、補走或補休息。",
            noteEn: "Let the weather decide whether this becomes a re-shoot, a short walk, or a rest window.",
            durationMinutes: 180,
          },
        ],
      },
    ],
  },
  {
    _id: "mock-norway-arctic-drive",
    titleZh: "北挪威 8 天極光與海岸線路線",
    titleEn: "8-Day Arctic Coast and Aurora Route",
    slug: "arctic-coast-aurora-8d",
    descriptionZh: "給想把公路感、冬季景色和夜晚極光體驗綁在一起的深度版本。",
    descriptionEn: "A longer northern route built around winter drives, coastal scenery, and aurora nights.",
    country: "Norway",
    purpose: "adventure",
    transportMode: "car",
    pace: "intensive",
    budget: "premium",
    seasons: ["autumn", "winter"],
    arrivalTime: "night",
    departureTime: "noon",
    durationDays: 8,
    featured: false,
    days: [
      {
        dayNumber: 1,
        titleZh: "晚到與入住",
        titleEn: "Late Arrival and Check-in",
        summaryZh: "把第一天設計成保守一點，為後面幾天留精神。",
        summaryEn: "Keep day one intentionally light so the rest of the route has more energy.",
        stops: [
          {
            time: "21:00",
            labelZh: "機場取車與入住",
            labelEn: "Pick Up Car and Check In",
            noteZh: "冬季路況不熟時，第一晚不要再硬排遠距離移動。",
            noteEn: "On winter roads, avoid a long transfer on the first night.",
            durationMinutes: 90,
            hotelAdviceZh: "優先選有停車和晚入住彈性的住宿。",
            hotelAdviceEn: "Prioritize a stay with parking and flexible late check-in.",
          },
        ],
      },
      {
        dayNumber: 2,
        titleZh: "海岸線長距離移動",
        titleEn: "Long Scenic Coast Drive",
        summaryZh: "把今天當成真正的 Arctic roadtrip 章節。",
        summaryEn: "Treat this as the core Arctic roadtrip chapter of the route.",
        stops: [
          {
            time: "11:00",
            labelZh: "海岸休息點",
            labelEn: "Coastal Pull-over",
            noteZh: "保留好幾次短停，讓長車程不會疲乏。",
            noteEn: "Plan several short stops so the long drive stays enjoyable.",
            durationMinutes: 45,
            photoTipZh: "陰天海面反而更有層次，不用只等晴天。",
            photoTipEn: "Cloudy skies often add more texture to the water than full sun.",
          },
        ],
      },
    ],
  },
  {
    _id: "mock-nz-south-classic-loop",
    titleZh: "紐西蘭南島 7 天經典自駕",
    titleEn: "Classic South Island Drive in 7 Days",
    slug: "south-island-classic-7d",
    descriptionZh: "基督城、Tekapo、Queenstown 到 Milford Sound 的一條節奏穩定的經典線。",
    descriptionEn: "A steady first-time South Island route linking Christchurch, Tekapo, Queenstown, and Milford Sound.",
    country: "New Zealand",
    purpose: "see_all",
    transportMode: "car",
    pace: "moderate",
    budget: "mid_range",
    seasons: ["spring", "summer", "autumn"],
    arrivalTime: "morning",
    departureTime: "night",
    durationDays: 7,
    featured: true,
    days: [
      {
        dayNumber: 1,
        titleZh: "基督城到 Tekapo",
        titleEn: "Christchurch to Tekapo",
        summaryZh: "第一天就把城市與湖區切換做出來，讓後面幾天更有層次。",
        summaryEn: "Move from city energy into lake country on day one to set up the rest of the route.",
        stops: [
          {
            time: "09:30",
            labelZh: "基督城出發",
            labelEn: "Depart Christchurch",
            noteZh: "先補採買和咖啡，再正式進入長距離駕駛。",
            noteEn: "Handle groceries and coffee first, then start the longer drive.",
            durationMinutes: 60,
          },
          {
            time: "15:30",
            labelZh: "Lake Tekapo 黃昏散步",
            labelEn: "Lake Tekapo Sunset Walk",
            noteZh: "下午到傍晚是最舒服的湖區入場時間。",
            noteEn: "Late afternoon is the easiest and most photogenic arrival window for Tekapo.",
            durationMinutes: 90,
            photoTipZh: "天色還沒全暗時，湖面和山線會更柔和。",
            photoTipEn: "Shoot before full dusk for softer lake and mountain tones.",
            hotelAdviceZh: "Tekapo 只住一晚就夠，把時間留給後面公路。",
            hotelAdviceEn: "One night in Tekapo is usually enough for this pace.",
          },
        ],
      },
      {
        dayNumber: 2,
        titleZh: "湖區往皇后鎮",
        titleEn: "Lakes Region to Queenstown",
        summaryZh: "把公路風景和城市感銜接起來，不急著在單點停太久。",
        summaryEn: "Blend scenic driving with a smooth entry into Queenstown without overcommitting to one stop.",
        stops: [
          {
            time: "11:00",
            labelZh: "途中觀景與午餐",
            labelEn: "Scenic Pull-over and Lunch",
            noteZh: "用一個正式午餐切開路程，整天會舒服很多。",
            noteEn: "A proper lunch stop makes the whole drive feel more balanced.",
            durationMinutes: 75,
            mealAdviceZh: "避免排太熱門的店，公路日重點是節奏不是打卡。",
            mealAdviceEn: "Don't optimize this day around a famous restaurant; keep the rhythm smooth.",
          },
        ],
      },
      {
        dayNumber: 3,
        titleZh: "皇后鎮彈性日",
        titleEn: "Flexible Queenstown Day",
        summaryZh: "留給纜車、步道、咖啡館或補眠的一天。",
        summaryEn: "A flexible day for viewpoints, short walks, cafes, or simply resting.",
        stops: [
          {
            time: "10:30",
            labelZh: "市區與湖邊",
            labelEn: "Town and Lakefront",
            noteZh: "今天的重點是不要把 schedule 填滿。",
            noteEn: "The point today is to avoid filling every hour.",
            durationMinutes: 180,
            personalAdviceZh: "南島行程真正好用的地方，是知道哪一天要故意放慢。",
            personalAdviceEn: "The best South Island itineraries know exactly when to slow down on purpose.",
          },
        ],
      },
    ],
  },
  {
    _id: "mock-nz-adventure-south",
    titleZh: "紐西蘭南島 5 天冒險節奏版",
    titleEn: "5-Day South Island Adventure Pace",
    slug: "south-island-adventure-5d",
    descriptionZh: "適合時間比較短，但希望每天都保有移動感與探索感的版本。",
    descriptionEn: "A shorter, faster-moving version for travelers who still want each day to feel active and exploratory.",
    country: "New Zealand",
    purpose: "adventure",
    transportMode: "mixed",
    pace: "intensive",
    budget: "premium",
    seasons: ["summer", "autumn"],
    arrivalTime: "noon",
    departureTime: "morning",
    durationDays: 5,
    featured: false,
    days: [
      {
        dayNumber: 1,
        titleZh: "直接進山景節奏",
        titleEn: "Jump Straight into the Mountain Rhythm",
        summaryZh: "不在城市停太久，快速把感官拉進南島的戶外尺度。",
        summaryEn: "Move quickly past the city so the trip starts in the outdoor scale of the South Island.",
        stops: [
          {
            time: "14:00",
            labelZh: "第一段移動",
            labelEn: "First Transfer Window",
            noteZh: "用一段明確移動把整個 trip mode 打開。",
            noteEn: "Use the first transfer to switch fully into trip mode.",
            durationMinutes: 150,
          },
        ],
      },
      {
        dayNumber: 2,
        titleZh: "高密度景觀日",
        titleEn: "High-Density Scenic Day",
        summaryZh: "這天以多個中短停點堆出強烈節奏。",
        summaryEn: "Build momentum with several medium and short stops across the day.",
        stops: [
          {
            time: "08:30",
            labelZh: "晨間觀景點",
            labelEn: "Morning Viewpoint",
            noteZh: "早一點出門，能避開人潮與逆光。",
            noteEn: "An early start helps with both crowds and harsher light.",
            durationMinutes: 50,
            photoTipZh: "清晨光線比正午更適合山景。",
            photoTipEn: "Morning light is noticeably kinder to mountain scenery than midday light.",
          },
        ],
      },
    ],
  },
];

export const MOCK_FEATURED_ITINERARIES = MOCK_ITINERARIES.filter((itinerary) => itinerary.featured);

export function getMockItinerariesByCountry(country) {
  return MOCK_ITINERARIES.filter((itinerary) => itinerary.country === country);
}
