export const MOCK_ITINERARIES = [
  {
    _id: "mock-norway-lofoten-summer-loop",
    titleZh: "羅弗敦群島 5 天 Lofoten 精選",
    titleEn: "Lofoten Essentials in 5 Days",
    slug: "lofoten-highlights-5d",
    descriptionZh: "以 Leknes、Å、Reine、Svolvær 和 Henningsvær 串起來的 Lofoten 初訪經典線。",
    descriptionEn: "A first-time Lofoten route built around Leknes, Å, Reine, Svolvaer, and Henningsvaer.",
    country: "Norway",
    purpose: "leisure",
    transportMode: "car",
    pace: "moderate",
    budget: "mid_range",
    seasons: ["summer", "autumn"],
    arrivalTime: "noon",
    departureTime: "morning",
    durationDays: 5,
    featured: true,
    days: [
      {
        dayNumber: 1,
        titleZh: "抵達與海港開場",
        titleEn: "Arrival and Southbound Intro",
        summaryZh: "從 Leknes 取車後直接進入 Lofoten 的海灘、超市補給與 Å 鎮節奏。",
        summaryEn: "Pick up the car in Leknes and move straight into the beaches, groceries, and Å village rhythm.",
        stops: [
          {
            time: "07:30",
            labelZh: "Leknes 機場取車",
            labelEn: "Pick Up Car at Leknes Airport",
            noteZh: "先熟悉當地限速提示，從 Leknes 開去 Hauklandstranda Beach 當作第一段暖身。",
            noteEn: "Start by getting used to the local speed cues and use the drive to Hauklandstranda Beach as your warm-up.",
            durationMinutes: 120,
            photoTipZh: "海灘邊的停車區就能拍到很乾淨的山海線條。",
            photoTipEn: "The parking area already gives you a clean mountain-meets-sea frame.",
            mealAdviceZh: "中午以前可以先在超市補齊水和簡單糧食，南下會更從容。",
            mealAdviceEn: "Grab water and easy groceries before heading south so the day stays flexible.",
          },
          {
            time: "13:30",
            labelZh: "Å 鎮與入住 Eliassen Rorbuer",
            labelEn: "Arrive in Å and Check in at Eliassen Rorbuer",
            noteZh: "南下途中邊開邊停拍照，16 點左右天黑前抵達 Å 鎮入住。",
            noteEn: "Work your way south with photo stops and aim to reach Å before the early winter sunset.",
            durationMinutes: 150,
            hotelAdviceZh: "直接住 Eliassen Rorbuer，隔天一早橋上拍照最順。",
            hotelAdviceEn: "Stay at Eliassen Rorbuer so you can shoot the bridge view first thing the next morning.",
          },
        ],
      },
      {
        dayNumber: 2,
        titleZh: "Reine 到 Svolvær",
        titleEn: "Reine to Svolvaer",
        summaryZh: "早上拍 Reine，午餐吃 Anita's Sjomat，下午沿 E10 一路開到 Svolvær。",
        summaryEn: "Start in Reine, stop for Anita's Sjomat, and finish with the E10 drive to Svolvaer.",
        stops: [
          {
            time: "08:00",
            labelZh: "Eliassen / Reine 拍照",
            labelEn: "Eliassen / Reine Photo Window",
            noteZh: "先在橋上拍 Eliassen Rorbuer，再到 Reine 補經典角度。",
            noteEn: "Begin at the bridge over Eliassen Rorbuer, then move on to the iconic Reine viewpoints.",
            durationMinutes: 60,
            photoTipZh: "早上光線比較乾淨，橋上構圖也最完整。",
            photoTipEn: "Morning light is cleaner, and the bridge gives you the strongest full-frame composition.",
          },
          {
            time: "12:30",
            labelZh: "Anita's Sjomat -> Svolvær",
            labelEn: "Anita's Sjomat -> Svolvaer",
            noteZh: "午餐吃魚漢堡後沿 E10 公路往 Svolvær 開，晚上在市中心逛紀念品店與超市。",
            noteEn: "Have fish burgers at Anita's Sjomat, then drive the E10 to Svolvaer for an evening in town.",
            durationMinutes: 240,
            mealAdviceZh: "Anita's Sjomat 的 classic 魚漢堡很適合這天當主餐。",
            mealAdviceEn: "The classic fish burger at Anita's Sjomat is a natural lunch anchor for this day.",
            personalAdviceZh: "凌晨若天氣好，可以衝 Austnesfjorden rasteplass 追極光。",
            personalAdviceEn: "If the weather is clear, Austnesfjorden rasteplass is a strong late-night aurora option.",
          },
        ],
      },
      {
        dayNumber: 3,
        titleZh: "Kabelvåg / Tjeldbergtind / Henningsvær",
        titleEn: "Kabelvag / Tjeldbergtind / Henningsvaer",
        summaryZh: "用 Kabelvåg、高處步道、Henningsvær 和 Uttakleiv 收掉 Lofoten 節奏。",
        summaryEn: "Finish the Lofoten rhythm with Kabelvag, a short hike, Henningsvaer, and Uttakleiv.",
        stops: [
          {
            time: "09:00",
            labelZh: "Kabelvåg + Tjeldbergtind",
            labelEn: "Kabelvag + Tjeldbergtind",
            noteZh: "先在 Kabelvåg 小鎮和高處看風景，再安排來回約 45 分鐘的 Tjeldbergtind。",
            noteEn: "Start with Kabelvag and the higher viewpoint, then add the short Tjeldbergtind hike.",
            durationMinutes: 180,
          },
          {
            time: "14:00",
            labelZh: "Henningsvær + Uttakleiv strand",
            labelEn: "Henningsvaer + Uttakleiv strand",
            noteZh: "下午去 Henningsvær 附近隨意逛逛拍照，最後收在 Uttakleiv 海灘。",
            noteEn: "Spend the afternoon wandering Henningsvaer and end the day at Uttakleiv beach.",
            durationMinutes: 210,
            hotelAdviceZh: "晚上可續住 Sennesvik 一帶，隔天移動比較順。",
            hotelAdviceEn: "Staying around Sennesvik keeps the following departure easier.",
          },
        ],
      },
    ],
  },
  {
    _id: "mock-norway-arctic-drive",
    titleZh: "北挪威 8 天極光與海岸線路線",
    titleEn: "8-Day Arctic Coast and Aurora Route",
    slug: "arctic-coast-aurora-8d",
    descriptionZh: "給想把公路感、冬季景色和夜晚極光體驗綁在一起的深度版本。",
    descriptionEn: "A longer northern route built around winter drives, coastal scenery, and aurora nights.",
    country: "Norway",
    purpose: "adventure",
    transportMode: "car",
    pace: "intensive",
    budget: "premium",
    seasons: ["autumn", "winter"],
    arrivalTime: "night",
    departureTime: "noon",
    durationDays: 8,
    featured: false,
    days: [
      {
        dayNumber: 1,
        titleZh: "晚到與入住",
        titleEn: "Late Arrival and Check-in",
        summaryZh: "把第一天設計成保守一點，為後面幾天留精神。",
        summaryEn: "Keep day one intentionally light so the rest of the route has more energy.",
        stops: [
          {
            time: "21:00",
            labelZh: "機場取車與入住",
            labelEn: "Pick Up Car and Check In",
            noteZh: "冬季路況不熟時，第一晚不要再硬排遠距離移動。",
            noteEn: "On winter roads, avoid a long transfer on the first night.",
            durationMinutes: 90,
            hotelAdviceZh: "優先選有停車和晚入住彈性的住宿。",
            hotelAdviceEn: "Prioritize a stay with parking and flexible late check-in.",
          },
        ],
      },
      {
        dayNumber: 2,
        titleZh: "海岸線長距離移動",
        titleEn: "Long Scenic Coast Drive",
        summaryZh: "把今天當成真正的 Arctic roadtrip 章節。",
        summaryEn: "Treat this as the core Arctic roadtrip chapter of the route.",
        stops: [
          {
            time: "11:00",
            labelZh: "海岸休息點",
            labelEn: "Coastal Pull-over",
            noteZh: "保留好幾次短停，讓長車程不會疲乏。",
            noteEn: "Plan several short stops so the long drive stays enjoyable.",
            durationMinutes: 45,
            photoTipZh: "陰天海面反而更有層次，不用只等晴天。",
            photoTipEn: "Cloudy skies often add more texture to the water than full sun.",
          },
        ],
      },
    ],
  },
  {
    _id: "mock-nz-south-classic-loop",
    titleZh: "紐西蘭南島 7 天經典自駕",
    titleEn: "Classic South Island Drive in 7 Days",
    slug: "south-island-classic-7d",
    descriptionZh: "以 Christchurch、Akaroa、Tekapo、Mount Cook 為前段主軸的南島經典線。",
    descriptionEn: "A South Island classic whose early rhythm is built around Christchurch, Akaroa, Tekapo, and Mount Cook.",
    country: "New Zealand",
    purpose: "see_all",
    transportMode: "car",
    pace: "moderate",
    budget: "mid_range",
    seasons: ["spring", "summer", "autumn"],
    arrivalTime: "morning",
    departureTime: "night",
    durationDays: 7,
    featured: true,
    days: [
      {
        dayNumber: 1,
        titleZh: "Christchurch 到 Akaroa",
        titleEn: "Christchurch to Akaroa",
        summaryZh: "下午抵達基督城後，先採買再一路開到 Akaroa 海邊小鎮。",
        summaryEn: "Land in Christchurch, stock up, and head out to the seaside town of Akaroa.",
        stops: [
          {
            time: "15:30",
            labelZh: "Woolworths Hornby 採買",
            labelEn: "Woolworths Hornby Grocery Stop",
            noteZh: "落地後先補齊食物和水，再往 Akaroa 方向出發。",
            noteEn: "Make your grocery stop first so the drive to Akaroa stays easy.",
            durationMinutes: 45,
          },
          {
            time: "17:30",
            labelZh: "Akaroa Harbour View -> 海邊主街",
            labelEn: "Akaroa Harbour View -> Waterfront Main Street",
            noteZh: "先看 Akaroa Harbour View / Hilltop，再進市區走 Peninsula War Memorial 和海邊。",
            noteEn: "Start with Akaroa Harbour View / Hilltop, then continue into town for the memorial and waterfront.",
            durationMinutes: 150,
            mealAdviceZh: "晚餐可選 Ma Maison 或 Akaroa Fish & Chips。",
            mealAdviceEn: "Dinner can be Ma Maison or Akaroa Fish & Chips.",
            hotelAdviceZh: "入住 Akaroa Waterfront Motels。",
            hotelAdviceEn: "Stay at Akaroa Waterfront Motels.",
          },
        ],
      },
      {
        dayNumber: 2,
        titleZh: "Akaroa 到 Lake Tekapo",
        titleEn: "Akaroa to Lake Tekapo",
        summaryZh: "早上牧場行程，下午經 Fairlie 進 Tekapo，晚上接湖邊步道。",
        summaryEn: "Start with alpacas, then drive via Fairlie into Tekapo for an evening lake rhythm.",
        stops: [
          {
            time: "11:00",
            labelZh: "Shamarra Alpacas -> Fairlie",
            labelEn: "Shamarra Alpacas -> Fairlie",
            noteZh: "上午先去 Shamarra Alpacas，途中在 Ashburton South 補給。",
            noteEn: "Visit Shamarra Alpacas in the morning and restock near Ashburton South on the way.",
            durationMinutes: 150,
          },
          {
            time: "16:30",
            labelZh: "Fairlie Bakehouse -> Tekapo",
            labelEn: "Fairlie Bakehouse -> Tekapo",
            noteZh: "傍晚在 Fairlie Bakehouse 吃鮭魚派，進 Tekapo 看好牧羊人教堂和湖邊步道。",
            noteEn: "Stop for salmon pie at Fairlie Bakehouse before arriving in Tekapo for the church and lake walk.",
            durationMinutes: 150,
            mealAdviceZh: "Fairlie Bakehouse 的 Salmon Pie 很值得當途中主餐。",
            mealAdviceEn: "Fairlie Bakehouse's salmon pie is worth making the main meal stop.",
            hotelAdviceZh: "入住 Olive Sanctuary - Discover Tekapo。",
            hotelAdviceEn: "Stay at Olive Sanctuary - Discover Tekapo.",
          },
        ],
      },
      {
        dayNumber: 3,
        titleZh: "Tekapo 到 Mount Cook",
        titleEn: "Tekapo to Mount Cook",
        summaryZh: "用 Pukaki、鮭魚店、Glacier Explorers 與 Hooker Valley Track 組成最強的一天。",
        summaryEn: "Turn day three into the strongest scenic day with Pukaki, salmon, Glacier Explorers, and Hooker Valley.",
        stops: [
          {
            time: "09:00",
            labelZh: "Tekapo 飛行 / Mt John -> Lake Pukaki",
            labelEn: "Tekapo Flight / Mt John -> Lake Pukaki",
            noteZh: "早上安排 Air Safaris 或 Mt John Observatory，途中停 Lake Pukaki Viewing Spot。",
            noteEn: "Use the morning for Air Safaris or Mt John Observatory, then stop by Lake Pukaki.",
            durationMinutes: 180,
          },
          {
            time: "13:00",
            labelZh: "Mount Cook 午餐與步道",
            labelEn: "Mount Cook Lunch and Walks",
            noteZh: "中午吃 Mt Cook Alpine Salmon Shop，下午做 Glacier Explorers 或 Hooker Valley Track。",
            noteEn: "Lunch at Mt Cook Alpine Salmon Shop, then Glacier Explorers or Hooker Valley Track in the afternoon.",
            durationMinutes: 270,
            mealAdviceZh: "Mt Cook Alpine Salmon Shop 很適合當今天的主餐停點。",
            mealAdviceEn: "Mt Cook Alpine Salmon Shop makes the right anchor lunch stop for this day.",
            personalAdviceZh: "如果 Glacier Explorers 時間卡太死，就把 Hooker Valley Track 留給主角。",
            personalAdviceEn: "If Glacier Explorers feels too rigid, let Hooker Valley Track take the lead.",
          },
        ],
      },
    ],
  },
  {
    _id: "mock-nz-adventure-south",
    titleZh: "紐西蘭南島 5 天冒險節奏版",
    titleEn: "5-Day South Island Adventure Pace",
    slug: "south-island-adventure-5d",
    descriptionZh: "適合時間比較短，但希望每天都保有移動感與探索感的版本。",
    descriptionEn: "A shorter, faster-moving version for travelers who still want each day to feel active and exploratory.",
    country: "New Zealand",
    purpose: "adventure",
    transportMode: "mixed",
    pace: "intensive",
    budget: "premium",
    seasons: ["summer", "autumn"],
    arrivalTime: "noon",
    departureTime: "morning",
    durationDays: 5,
    featured: false,
    days: [
      {
        dayNumber: 1,
        titleZh: "直接進山景節奏",
        titleEn: "Jump Straight into the Mountain Rhythm",
        summaryZh: "不在城市停太久，快速把感官拉進南島的戶外尺度。",
        summaryEn: "Move quickly past the city so the trip starts in the outdoor scale of the South Island.",
        stops: [
          {
            time: "14:00",
            labelZh: "第一段移動",
            labelEn: "First Transfer Window",
            noteZh: "用一段明確移動把整個 trip mode 打開。",
            noteEn: "Use the first transfer to switch fully into trip mode.",
            durationMinutes: 150,
          },
        ],
      },
      {
        dayNumber: 2,
        titleZh: "高密度景觀日",
        titleEn: "High-Density Scenic Day",
        summaryZh: "這天以多個中短停點堆出強烈節奏。",
        summaryEn: "Build momentum with several medium and short stops across the day.",
        stops: [
          {
            time: "08:30",
            labelZh: "晨間觀景點",
            labelEn: "Morning Viewpoint",
            noteZh: "早一點出門，能避開人潮與逆光。",
            noteEn: "An early start helps with both crowds and harsher light.",
            durationMinutes: 50,
            photoTipZh: "清晨光線比正午更適合山景。",
            photoTipEn: "Morning light is noticeably kinder to mountain scenery than midday light.",
          },
        ],
      },
    ],
  },
];

export const MOCK_FEATURED_ITINERARIES = MOCK_ITINERARIES.filter((itinerary) => itinerary.featured);

export function getMockItinerariesByCountry(country) {
  return MOCK_ITINERARIES.filter((itinerary) => itinerary.country === country);
}
